spring:
  application:
    name: hello-demo
  datasource:
    url: jdbc:mysql://47.98.173.88:3306/test
    username: root
    password: 123qweasdl_RR520.xu
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: admin
    password: admin
server:
  port: 8001
juxin:
  name: juxin
  age: 30
  header: '{cipher}17ff619433f0699de7e13f0f96abb316484ad27ab7410654cf86eb6fc86b367a'