spring:
  application:
    name: hello-demo
  datasource:
    url: jdbc:mysql://47.98.173.88:3306/test
    username: root
    password: 123qweasdl_RR520.xu
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8001
juxin:
  name: juxin
  age: 18